import { Product } from '@/types';

const local = (name: string) => `/products/${name}.jpg`;
export const products: Product[] = [
  { id:'1',slug:'iphone-15-pro',title:'گوشی موبایل اپل مدل iPhone 15 Pro ظرفیت 256 گیگابایت',brand:'Apple',image:local('tech-photo'),images:[local('tech-photo')],price:76500000,originalPrice:82500000,rating:4.7,reviewCount:284,colors:[{name:'تیتانیوم طبیعی',hex:'#a69c90'},{name:'مشکی',hex:'#242424'}],storage:['128 گیگابایت','256 گیگابایت','512 گیگابایت'],stock:8,category:'mobile',specs:{برند:'اپل',مدل:'iPhone 15 Pro',حافظه:'256 گیگابایت',شبکه:'5G'},description:'تجربه‌ای حرفه‌ای از سرعت، دوربین و طراحی تیتانیومی اپل.'},
  { id:'2',slug:'sony-headphones',title:'هدفون بی‌سیم سونی مدل WH-1000XM5',brand:'Sony',image:local('tech-photo'),images:[local('tech-photo')],price:18900000,originalPrice:21500000,rating:4.8,reviewCount:112,colors:[{name:'مشکی',hex:'#252525'},{name:'کرم',hex:'#d4c4ae'}],stock:12,category:'digital',specs:{برند:'Sony',نوع:'روگوشی',اتصال:'بلوتوث'},description:'حذف نویز هوشمند و صدایی شفاف برای هر لحظه.'},
  { id:'3',slug:'samsung-watch',title:'ساعت هوشمند سامسونگ مدل Galaxy Watch6 Classic',brand:'Samsung',image:local('tech-photo'),images:[local('tech-photo')],price:12950000,rating:4.5,reviewCount:76,colors:[{name:'مشکی',hex:'#1d1d1d'}],stock:3,category:'digital',specs:{برند:'Samsung',نوع:'هوشمند',نمایشگر:'AMOLED'},description:'همراهی شیک و هوشمند برای سلامت و زندگی روزمره.'},
  { id:'4',slug:'canon-camera',title:'دوربین دیجیتال کانن مدل EOS R10 با لنز 18-45',brand:'Canon',image:local('tech-photo'),images:[local('tech-photo')],price:54800000,originalPrice:59900000,rating:4.6,reviewCount:53,colors:[{name:'مشکی',hex:'#222'}],stock:5,category:'digital',specs:{برند:'Canon',حسگر:'APS-C',رزولوشن:'24.2 مگاپیکسل'},description:'ثبت لحظه‌ها با جزئیات خیره‌کننده.'},
  { id:'5',slug:'nike-air-max',title:'کفش راحتی نایک مدل Air Max 270',brand:'Nike',image:local('lifestyle-photo'),images:[local('lifestyle-photo')],price:6250000,originalPrice:7200000,rating:4.4,reviewCount:89,colors:[{name:'قرمز',hex:'#ca293d'}],stock:20,category:'fashion',specs:{برند:'Nike',جنس:'پارچه و چرم مصنوعی',مناسب:'روزمره'},description:'راحتی تمام‌روز با طراحی نمادین نایک.'},
  { id:'6',slug:'coffee-machine',title:'اسپرسوساز دلونگی مدل Dedica EC685',brand:'DeLonghi',image:local('lifestyle-photo'),images:[local('lifestyle-photo')],price:14500000,rating:4.6,reviewCount:41,colors:[{name:'استیل',hex:'#b8b8b8'}],stock:7,category:'home',specs:{برند:'DeLonghi',توان:'1350 وات',فشار:'15 بار'},description:'اسپرسوی حرفه‌ای در آشپزخانه‌ی شما.'},
  { id:'7',slug:'macbook-air-m3',title:'لپ‌تاپ اپل MacBook Air M3 مدل 2024',brand:'Apple',image:local('home-photo'),images:[local('home-photo')],price:69500000,originalPrice:71000000,rating:4.9,reviewCount:65,colors:[{name:'نقره‌ای',hex:'#cfd1d2'}],storage:['256 گیگابایت','512 گیگابایت'],stock:4,category:'laptop',specs:{برند:'Apple',پردازنده:'M3',نمایشگر:'13.6 اینچ'},description:'لپ‌تاپی سبک، سریع و آماده‌ی کارهای بزرگ.'},
  { id:'8',slug:'samsung-qled-tv',title:'تلویزیون هوشمند سامسونگ QLED سایز 55 اینچ',brand:'Samsung',image:local('home-photo'),images:[local('home-photo')],price:38500000,originalPrice:42000000,rating:4.3,reviewCount:38,colors:[{name:'مشکی',hex:'#1e2022'}],stock:0,category:'home',specs:{برند:'Samsung',سایز:'55 اینچ',کیفیت:'4K'},description:'تصویری زنده و سینمایی در قلب خانه شما.'},
  { id:'9',slug:'leather-bag',title:'کیف دوشی زنانه چرم طبیعی مدل آوینا',brand:'Avina',image:local('lifestyle-photo'),images:[local('lifestyle-photo')],price:2950000,originalPrice:3400000,rating:4.2,reviewCount:31,colors:[{name:'قهوه‌ای',hex:'#6f4437'}],stock:13,category:'fashion',specs:{جنس:'چرم طبیعی',نوع:'دوشی'},description:'کیفی ظریف با کیفیت دوخت ممتاز.'},
  { id:'10',slug:'playstation-5-slim',title:'کنسول بازی سونی PlayStation 5 Slim',brand:'Sony',image:local('home-photo'),images:[local('home-photo')],price:39500000,rating:4.9,reviewCount:201,colors:[{name:'سفید',hex:'#f3f4f6'}],stock:6,category:'gaming',specs:{برند:'Sony',حافظه:'1 ترابایت',نسل:'نهم'},description:'دنیای بازی‌ها را با سرعت و جزئیات نفس‌گیر تجربه کنید.'},
  { id:'11',slug:'philips-blender',title:'مخلوط‌کن فیلیپس مدل HR2223',brand:'Philips',image:local('home-photo'),images:[local('home-photo')],price:4850000,rating:4.1,reviewCount:17,colors:[{name:'آبی',hex:'#5d8d91'}],stock:9,category:'home',specs:{برند:'Philips',توان:'700 وات',ظرفیت:'2 لیتر'},description:'برای نوشیدنی‌ها و غذاهای خانگی تازه و سریع.'},
  { id:'12',slug:'book-design',title:'کتاب هنر شفاف اندیشیدن اثر رولف دوبلی',brand:'نشر چشمه',image:local('lifestyle-photo'),images:[local('lifestyle-photo')],price:265000,rating:4.7,reviewCount:104,colors:[{name:'کرم',hex:'#ead9cf'}],stock:31,category:'book',specs:{نویسنده:'رولف دوبلی',ناشر:'چشمه',زبان:'فارسی'},description:'کتابی برای بهتر فکر کردن و تصمیم‌های دقیق‌تر.'}
];
const delay=<T,>(data:T):Promise<T> => new Promise(resolve=>setTimeout(()=>resolve(data),250));
export const productService={getFeatured:()=>delay(products),getBySlug:(slug:string)=>delay(products.find(p=>p.slug===slug)),search:(query:string)=>delay(products.filter(p=>p.title.includes(query)||p.brand.toLowerCase().includes(query.toLowerCase()))),getRelated:(category:string)=>delay(products.filter(p=>p.category===category).slice(0,4))};
